// src/models/enums.ts
export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  MERCHANT = 'MERCHANT',
}

export enum AddressType {
  HOME = 'HOME',
  OFFICE = 'OFFICE',
}

export enum StoreStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  BANNED = 'BANNED',
}

export enum BankAccountStatus {
  PENDING = 'PENDING',
  APPROVED = 'VERIFIED',
  BANNED = 'FAILED',
}

export enum ShippingType {
  STANDARD = 'STANDARD',
  EXPRESS = 'EXPRESS',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  OUT_OF_STOCK = 'OUT_OF_STOCK'
}

export enum OrderStatus {
  PENDING = "PENDING",
  CUSTOMER_CANCELED = "CUSTOMER_CANCELED",
  PAID = "PAID",
  MERCHANT_REJECT = "MERCHANT_CANCELED",
  PROCESSING = "PROCESSING",
  READY_TO_SHIP = "READY_TO_SHIP",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  REFUND_REQUEST = "REFUND_REQUEST",
  TRANSIT_LACK = "TRANSIT_LACK",
  RE_TRANSIT = "RE_TRANSIT",
  AWAITING_RETURN = "AWAITING_RETURN",
  RECIEVE_RETURN = "RECEIVE_RETURN",
  RETURN_FAIL = "RETURN_FAIL",
  RETURN_VERIFIED = "RETURN_VERIFIED",
  REFUND_APPROVED = "REFUND_APPROVED",
  REFUND_FAIL = "REFUND_FAIL",
  REFUND_SUCCESS = "REFUND_SUCCESS",
  COMPLETE = "COMPLETE",
}

export enum PaymentStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
}

export enum ShippingStatus {
  PENDING = 'PENDING',
  IN_TRANSIT = 'IN_TRANSIT',
  CUSTOMER_REJECT = 'CUSTOMER_REJECT',
  TRANSIT_ISSUE = 'TRANSIT_ISSUE',
  RE_TRANSIT = 'RE_TRANSIT',
  DELIVERED = 'DELIVERED',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}