// seeders/20250721000002-seed-order-status-history.ts
import { QueryInterface } from "sequelize"

export default {
  up: async (queryInterface: QueryInterface) => {
    const now = new Date()

    await queryInterface.bulkInsert("ORDER_STATUS_HISTORY", [
      // Order 6001: PENDING
      {
        order_id: 6001,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6001",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6002: CUSTOMER_CANCELED
      {
        order_id: 6002,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6002-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6002,
        from_status: "PENDING",
        to_status: "CUSTOMER_CANCELED",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Customer canceled before payment",
        source: "WEB",
        correlation_id: "req-6002-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6003: PAID
      {
        order_id: 6003,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6003-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6003,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6003",
        metadata: JSON.stringify({ provider: "KBank" }),
        created_at: now,
        updated_at: now,
      },

      // Order 6004: PROCESSING
      {
        order_id: 6004,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6004-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6004,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6004",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6004,
        from_status: "PAID",
        to_status: "PROCESSING",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Merchant started processing",
        source: "DASHBOARD",
        correlation_id: "req-6004-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6005: READY_TO_SHIP
      {
        order_id: 6005,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6005-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6005,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6005",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6005,
        from_status: "PAID",
        to_status: "PROCESSING",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Processing order",
        source: "DASHBOARD",
        correlation_id: "req-6005-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6005,
        from_status: "PROCESSING",
        to_status: "READY_TO_SHIP",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Prepared for shipping",
        source: "DASHBOARD",
        correlation_id: "req-6005-c",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6006: SHIPPED
      {
        order_id: 6006,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6006-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6006,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6006",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6006,
        from_status: "PAID",
        to_status: "PROCESSING",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Processing order",
        source: "DASHBOARD",
        correlation_id: "req-6006-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6006,
        from_status: "PROCESSING",
        to_status: "READY_TO_SHIP",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Prepared for shipping",
        source: "DASHBOARD",
        correlation_id: "req-6006-c",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6006,
        from_status: "READY_TO_SHIP",
        to_status: "HANDED_OVER",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Prepared for shipping",
        source: "DASHBOARD",
        correlation_id: "req-6006-d",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6006,
        from_status: "HANDED_OVER",
        to_status: "SHIPPED",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Shipped out",
        source: "DASHBOARD",
        correlation_id: "req-6006-e",
        metadata: JSON.stringify({ carrier: "DHL" }),
        created_at: now,
        updated_at: now,
      },

      // Order 6007: DELIVERED
      {
        order_id: 6007,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6007-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6007",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "PAID",
        to_status: "PROCESSING",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Processing order",
        source: "DASHBOARD",
        correlation_id: "req-6007-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "PROCESSING",
        to_status: "READY_TO_SHIP",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Prepared",
        source: "DASHBOARD",
        correlation_id: "req-6007-c",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "READY_TO_SHIP",
        to_status: "HANDED_OVER",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Shipped",
        source: "DASHBOARD",
        correlation_id: "req-6007-d",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "HANDED_OVER",
        to_status: "SHIPPED",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Shipped",
        source: "DASHBOARD",
        correlation_id: "req-6007-e",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6007,
        from_status: "SHIPPED",
        to_status: "DELIVERED",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Received by customer",
        source: "SYSTEM",
        correlation_id: "req-6007-f",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6008: COMPLETE
      {
        order_id: 6008,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6008-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6008",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "PAID",
        to_status: "PROCESSING",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Processing",
        source: "DASHBOARD",
        correlation_id: "req-6008-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "PROCESSING",
        to_status: "READY_TO_SHIP",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Prepared",
        source: "DASHBOARD",
        correlation_id: "req-6008-c",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "READY_TO_SHIP",
        to_status: "HANDED_OVER",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Shipped",
        source: "DASHBOARD",
        correlation_id: "req-6008-d",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "HANDED_OVER",
        to_status: "SHIPPED",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Shipped",
        source: "DASHBOARD",
        correlation_id: "req-6008-e",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "SHIPPED",
        to_status: "DELIVERED",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Received",
        source: "SYSTEM",
        correlation_id: "req-6008-f",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6008,
        from_status: "DELIVERED",
        to_status: "COMPLETE",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Confirmed complete",
        source: "APP",
        correlation_id: "req-6008-g",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6009: REFUND_REQUEST
      {
        order_id: 6009,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6009-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6009,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6009",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6009,
        from_status: "PAID",
        to_status: "REFUND_REQUEST",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Requested refund",
        source: "APP",
        correlation_id: "req-6009-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },

      // Order 6010: REFUND_SUCCESS
      {
        order_id: 6010,
        from_status: null,
        to_status: "PENDING",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Order created",
        source: "API",
        correlation_id: "req-6010-a",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6010,
        from_status: "PENDING",
        to_status: "PAID",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Payment success",
        source: "WEBHOOK",
        correlation_id: "txn-6010",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6010,
        from_status: "PAID",
        to_status: "REFUND_REQUEST",
        changed_by_type: "CUSTOMER",
        changed_by_id: 1,
        reason: "Requested refund",
        source: "APP",
        correlation_id: "req-6010-b",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6010,
        from_status: "REFUND_REQUEST",
        to_status: "REFUND_APPROVED",
        changed_by_type: "MERCHANT",
        changed_by_id: 2,
        reason: "Refund approved",
        source: "DASHBOARD",
        correlation_id: "req-6010-c",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
      {
        order_id: 6010,
        from_status: "REFUND_APPROVED",
        to_status: "REFUND_SUCCESS",
        changed_by_type: "SYSTEM",
        changed_by_id: 0,
        reason: "Refund completed",
        source: "PAYMENT_GATEWAY",
        correlation_id: "txn-6010-refund",
        metadata: JSON.stringify({}),
        created_at: now,
        updated_at: now,
      },
    ])
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("ORDER_STATUS_HISTORY", {
      order_id: [6001,6002,6003,6004,6005,6006,6007,6008,6009,6010]
    })
  },
}
