import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert("SHIPPING_INFO", [
      {
        order_id: 6001,
        tracking_number: "TRK6001",
        carrier: "DHL",
        shipping_type_id: 1, // STANDARD
        shipping_status: "IN_TRANSIT",
        shipping_address: 1, // ต้องมี address_id = 1 อยู่จริง
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6002,
        tracking_number: "TRK6002",
        carrier: "Kerry",
        shipping_type_id: 2, // EXPRESS
        shipping_status: "IN_TRANSIT",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6003,
        tracking_number: "TRK6003",
        carrier: "Flash",
        shipping_type_id: 1,
        shipping_status: "DELIVERED",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6004,
        tracking_number: "TRK6004",
        carrier: "DHL",
        shipping_type_id: 2,
        shipping_status: "IN_TRANSIT",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6005,
        tracking_number: "TRK6005",
        carrier: "Kerry",
        shipping_type_id: 1,
        shipping_status: "PENDING",
        shipping_address: 1,
        shipped_at: null,
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6006,
        tracking_number: "TRK6006",
        carrier: "Flash",
        shipping_type_id: 2,
        shipping_status: "IN_TRANSIT",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6007,
        tracking_number: "TRK6007",
        carrier: "DHL",
        shipping_type_id: 1,
        shipping_status: "DELIVERED",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6008,
        tracking_number: "TRK6008",
        carrier: "Kerry",
        shipping_type_id: 2,
        shipping_status: "IN_TRANSIT",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6009,
        tracking_number: "TRK6009",
        carrier: "Flash",
        shipping_type_id: 1,
        shipping_status: "PENDING",
        shipping_address: 1,
        shipped_at: null,
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
      {
        order_id: 6010,
        tracking_number: "TRK6010",
        carrier: "DHL",
        shipping_type_id: 2,
        shipping_status: "IN_TRANSIT",
        shipping_address: 1,
        shipped_at: new Date(),
        created_at: new Date(),
        updated_at: new Date(),
        deleted_at: null,
      },
    ]);
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("SHIPPING_INFO", {
      order_id: [6001,6002,6003,6004,6005,6006,6007,6008,6009,6010],
    });
  },
};
