import { QueryInterface } from "sequelize"
import { v4 as uuidv4 } from "uuid"
const now = new Date();
export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert("PRODUCT_ITEMS", [
      {
        id: 1001,
        product_id:1001,
        sku: 'BLACK-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1002,
        product_id:1001,
        sku: 'WHITE-01',
        stock_quantity: 10,
        price_minor: 1750000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1003,
        product_id:1002,
        sku: 'BLACK-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1004,
        product_id:1002,
        sku: 'WHITE-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1005,
        product_id:1004,
        sku: 'WE-01',
        stock_quantity: 10,
        price_minor: 200000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1006,
        product_id:1003,
        sku: 'BLACK-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1007,
        product_id:1003,
        sku: 'GRAY-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1008,
        product_id:1004,
        sku: 'WE-02',
        stock_quantity: 10,
        price_minor: 300000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1009,
        product_id:1005,
        sku: 'BLACK-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
      {
        id: 1010,
        product_id:1005,
        sku: 'WHITE-01',
        stock_quantity: 10,
        price_minor: 1500000,
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
    ])
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("PRODUCT_ITEMS", {
      id: [1001, 1002],
    })
  },
}
