// src/seeders/2025xxxx-seed-refund-orders.ts
import { QueryInterface } from "sequelize";

export default {
  async up(queryInterface: QueryInterface) {
    const now = new Date();
    const thb = "THB";

    await queryInterface.bulkInsert("REFUND_ORDERS", [
      // 6013: ORDERS.status = REFUND_REQUEST  -> Refund = REQUESTED
      {
        order_id: 6013,
        payment_id: 13,
        reason: "เปลี่ยนใจ",
        merchant_reject_reason: null,
        amount_minor: 410000,
        currency_code: thb,
        status: "REQUESTED",
        refund_channel: null,
        refund_ref: null,
        description: "ขอคืนเงินก่อนจัดส่ง",
        contact_email: "customer6013@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-20T09:00:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "REFUND_REQUEST" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6014: AWAITING_RETURN -> REQUESTED
      {
        order_id: 6014,
        payment_id: 14,
        reason: "สีไม่ตรง",
        merchant_reject_reason: null,
        amount_minor: 250000,
        currency_code: thb,
        status: "REQUESTED",
        refund_channel: null,
        refund_ref: null,
        description: "ต้องการคืนหลังได้รับสินค้าแล้ว",
        contact_email: "customer6014@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-19T10:30:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "AWAITING_RETURN" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6015: RECEIVE_RETURN -> REQUESTED
      {
        order_id: 6015,
        payment_id: 15,
        reason: "สินค้ามีตำหนิ",
        merchant_reject_reason: null,
        amount_minor: 255000,
        currency_code: thb,
        status: "REQUESTED",
        refund_channel: null,
        refund_ref: null,
        description: "มีรอยขีดข่วนชัดเจน",
        contact_email: "customer6015@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-18T11:00:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "RECEIVE_RETURN" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6016: RETURN_VERIFIED -> REQUESTED
      {
        order_id: 6016,
        payment_id: 16,
        reason: "ไม่ตรงสเปค",
        merchant_reject_reason: null,
        amount_minor: 260000,
        currency_code: thb,
        status: "REQUESTED",
        refund_channel: null,
        refund_ref: null,
        description: "สเปค RAM/ROM ไม่ตรงประกาศ",
        contact_email: "customer6016@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-18T12:00:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "RETURN_VERIFIED" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6017: RETURN_FAIL -> FAIL
      {
        order_id: 6017,
        payment_id: 17,
        reason: "ส่งคืนไม่ทันกำหนด",
        merchant_reject_reason: "ส่งคืนเกินเวลา/อุปกรณ์ไม่ครบ",
        amount_minor: 265000,
        currency_code: thb,
        status: "FAIL",
        refund_channel: "PROMPTPAY",
        refund_ref: "RF-6017-FAIL",
        description: "ส่งคืนล่าช้าและขาดอุปกรณ์",
        contact_email: "customer6017@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-17T09:30:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: JSON.stringify({ code: "RETURN_NOT_ELIGIBLE" }),
        metadata: JSON.stringify({ stage: "RETURN_FAIL" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6018: REFUND_REJECTED -> FAIL
      {
        order_id: 6018,
        payment_id: 18,
        reason: "ไม่พอใจสินค้า",
        merchant_reject_reason: "ไม่เข้าเงื่อนไขตามนโยบายร้าน",
        amount_minor: 420000,
        currency_code: thb,
        status: "FAIL",
        refund_channel: null,
        refund_ref: null,
        description: "ใช้งานแล้ว สภาพไม่พร้อมคืน",
        contact_email: "customer6018@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-17T10:00:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "REFUND_REJECTED" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6019: REFUND_APPROVED -> APPROVED
      {
        order_id: 6019,
        payment_id: 19,
        reason: "ของมีตำหนิ",
        merchant_reject_reason: null,
        amount_minor: 430000,
        currency_code: thb,
        status: "APPROVED",
        refund_channel: null,
        refund_ref: null,
        description: "ตำหนิที่มุมเครื่อง",
        contact_email: "customer6019@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-16T08:45:00Z"),
        approved_at: new Date("2025-08-17T14:00:00Z"),
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "REFUND_APPROVED" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6020: REFUND_SUCCESS -> SUCCESS
      {
        order_id: 6020,
        payment_id: 20,
        reason: "กล่องบุบ/แพ็กไม่ดี",
        merchant_reject_reason: null,
        amount_minor: 510000,
        currency_code: thb,
        status: "SUCCESS",
        refund_channel: "CARD",
        refund_ref: "RF-6020-001",
        description: "แพ็กเกจบุบชัดเจน มีรูปประกอบ",
        contact_email: "customer6020@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-15T09:15:00Z"),
        approved_at: new Date("2025-08-16T10:00:00Z"),
        refunded_at: new Date("2025-08-16T12:30:00Z"),
        pgw_payload: JSON.stringify({ provider: "KBank" }),
        metadata: JSON.stringify({ stage: "REFUND_SUCCESS" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6021: REFUND_FAIL -> FAIL (PGW ล้มเหลว)
      {
        order_id: 6021,
        payment_id: 21,
        reason: "สินค้าไม่ทำงาน",
        merchant_reject_reason: null,
        amount_minor: 440000,
        currency_code: thb,
        status: "FAIL",
        refund_channel: "PROMPTPAY",
        refund_ref: "RF-6021-ERR",
        description: "เปิดไม่ติดแม้ชาร์จแบต",
        contact_email: "customer6021@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-15T10:00:00Z"),
        approved_at: new Date("2025-08-16T09:30:00Z"),
        refunded_at: null,
        pgw_payload: JSON.stringify({ error: "TIMEOUT" }),
        metadata: JSON.stringify({ stage: "REFUND_FAIL" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },

      // 6022: REFUND_REQUEST -> REQUESTED
      {
        order_id: 6022,
        payment_id: 22,
        reason: "เปลี่ยนใจ",
        merchant_reject_reason: null,
        amount_minor: 410000,
        currency_code: thb,
        status: "REQUESTED",
        refund_channel: null,
        refund_ref: null,
        description: "ขอคืนเงินหลังจัดส่ง",
        contact_email: "customer6013@example.com",
        requested_by: "CUSTOMER",
        requested_at: new Date("2025-08-20T09:00:00Z"),
        approved_at: null,
        refunded_at: null,
        pgw_payload: null,
        metadata: JSON.stringify({ stage: "REFUND_REQUEST" }),
        created_at: now,
        updated_at: now,
        deleted_at: null,
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    await queryInterface.bulkDelete("REFUND_ORDERS", {
      order_id: [6013,6014,6015,6016,6017,6018,6019,6020,6021,6022],
    });
  },
};
